In [8]:
import sys
sys.path.append('src')

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import logging

logging.basicConfig(level=logging.INFO)

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [9]:
from analytics.numpy_ops import demonstrate_array_creation, print_array_info, vectorized_operations, axis_reductions, broadcasting_example
from analytics.data_loader import load_from_mongodb, save_to_csv, chunked_stats, optimise_dtypes, memory_comparison

print("Modules loaded successfully!")

Modules loaded successfully!

In [10]:
import numpy as np

ratings = np.array([4.5, 3.2, 5.0, 2.8, 4.1, 3.9])
price_placeholder = np.zeros(6)
category_weights = np.ones((3, 4))
years = np.arange(2010, 2025)
score_buffer = np.empty((2, 3))
print("=== Array Info ===")
arrays = {
        'ratings': ratings,
        'price_placeholder': price_placeholder,
        'category_weights': category_weights,
        'years': years,
        'score_buffer': score_buffer,
    }
for name, arr in arrays.items():
        print(f'  {name:<22s} shape={str(arr.shape):<12} dtype={arr.dtype}  ndim={arr.ndim}  size={arr.size}')

ratings_arr = np.array([4.5, 3.2, 5.0, 2.8, 4.1, 3.9, 4.7, 2.5, 5.0, 3.6])
review_count = np.array([120, 45, 200, 30, 89, 67, 150, 25, 310, 55])

normalized = ratings_arr * 10
weighted   = ratings_arr * np.log(review_count)
high_rated = ratings_arr > 4.0
quality    = (ratings_arr > 3.5) & (review_count > 100)

print("\n=== Vectorized Operations ===")
print(f" mean : {ratings_arr.mean():.2f}")
print(f" std  : {ratings_arr.std():.2f}")
print(f" max  : {ratings_arr.max():.2f}")

print("\n=== Axis Reductions ===")
matrix = np.vstack([ratings_arr, review_count])
print(f" col_means: {matrix.mean(axis=0).round(2)}")
print(f" row_means: {matrix.mean(axis=1).round(2)}")

print("\n=== Broadcasting (normalized) ===")
min_v, max_v = ratings_arr.min(), ratings_arr.max()
normalized = (ratings_arr - min_v) / (max_v - min_v)
print(f" {normalized.round(3)}")

=== Array Info ===
  ratings                shape=(6,)         dtype=float64  ndim=1  size=6
  price_placeholder      shape=(6,)         dtype=float64  ndim=1  size=6
  category_weights       shape=(3, 4)       dtype=float64  ndim=2  size=12
  years                  shape=(15,)        dtype=int64  ndim=1  size=15
  score_buffer           shape=(2, 3)       dtype=float64  ndim=2  size=6

=== Vectorized Operations ===
 mean : 3.93
 std  : 0.85
 max  : 5.00

=== Axis Reductions ===
 col_means: [ 62.25  24.1  102.5   16.4   46.55  35.45  77.35  13.75 157.5   29.3 ]
 row_means: [  3.93 109.1 ]

=== Broadcasting (normalized) ===
 [0.8  0.28 1.   0.12 0.64 0.56 0.88 0.   1.   0.44]

In [11]:
import sys
sys.path.append('src')

from analytics.data_loader import load_from_mongodb, save_to_csv, chunked_stats, optimise_dtypes, memory_comparison

df = load_from_mongodb()
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
df.head(3)

INFO:analytics.data_loader:Connecting to MongoDB: ecommerce_product_intelligence / products
INFO:analytics.data_loader:Loaded 1427 rows from MongoDB

Shape: (1427, 58)
Columns: ['source', 'fetched_at', 'version', 'file_name', 'type', 'page_number', 'review_id', 'title', 'comment', 'rating', 'author', 'author_id', 'date', 'verified', 'helpful_votes', 'review_link', 'variant.Style', 'variant', 'text', 'text.paragraphs', 'text.tables', 'category', 'description', 'budgeted', 'actual', 'variance', 'variance_pct', 'status', 'notes', 'amount', 'type', 'running_balance', 'receipt', 'goal_name', 'target', 'saved', 'remaining', 'progress', 'eta', 'month', 'income', 'expenses', 'savings', 'net_flow', 'savings_rate', 'text.column_1', 'text.column_2', 'text.full_text', 'price', 'link', 'page_scraped', 'year', 'awards', 'nominations', 'best_picture', 'year_scraped', 'raw', 'preprocessed']

,source,fetched_at,version,file_name,type,page_number,review_id,title,comment,rating,...,price,link,page_scraped,year,awards,nominations,best_picture,year_scraped,raw,preprocessed
0,reviews_page_1.json,2026-03-22 09:22:25.843,1,NaN,NaN,NaN,R3HIEYXVQFRUBV,"Powerful, Versatile & Worth Every Penny!",I absolutely love this Ninja Kitchen System! I...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,reviews_page_1.json,2026-03-22 09:22:25.884,1,NaN,NaN,NaN,RYDWBH5RPKGBH,Powerful and versatile — love it!,The Ninja Kitchen System has been an amazing a...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,reviews_page_1.json,2026-03-22 09:22:25.886,1,NaN,NaN,NaN,R2ST6OORNLR2CO,Great blender,"Love this blender, it works great, very durabl...",5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
import sys
sys.path.append('src')

from analytics.data_loader import load_from_mongodb, save_to_csv, chunked_stats, optimise_dtypes, memory_comparison

df = load_from_mongodb()
print(f"Shape: {df.shape}")
print(f"Columns: {list(df.columns)}")
df.head(3)

INFO:analytics.data_loader:Connecting to MongoDB: ecommerce_product_intelligence / products
INFO:analytics.data_loader:Loaded 1427 rows from MongoDB

Shape: (1427, 58)
Columns: ['source', 'fetched_at', 'version', 'file_name', 'type', 'page_number', 'review_id', 'title', 'comment', 'rating', 'author', 'author_id', 'date', 'verified', 'helpful_votes', 'review_link', 'variant.Style', 'variant', 'text', 'text.paragraphs', 'text.tables', 'category', 'description', 'budgeted', 'actual', 'variance', 'variance_pct', 'status', 'notes', 'amount', 'type', 'running_balance', 'receipt', 'goal_name', 'target', 'saved', 'remaining', 'progress', 'eta', 'month', 'income', 'expenses', 'savings', 'net_flow', 'savings_rate', 'text.column_1', 'text.column_2', 'text.full_text', 'price', 'link', 'page_scraped', 'year', 'awards', 'nominations', 'best_picture', 'year_scraped', 'raw', 'preprocessed']

,source,fetched_at,version,file_name,type,page_number,review_id,title,comment,rating,...,price,link,page_scraped,year,awards,nominations,best_picture,year_scraped,raw,preprocessed
0,reviews_page_1.json,2026-03-22 09:22:25.843,1,NaN,NaN,NaN,R3HIEYXVQFRUBV,"Powerful, Versatile & Worth Every Penny!",I absolutely love this Ninja Kitchen System! I...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,reviews_page_1.json,2026-03-22 09:22:25.884,1,NaN,NaN,NaN,RYDWBH5RPKGBH,Powerful and versatile — love it!,The Ninja Kitchen System has been an amazing a...,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,reviews_page_1.json,2026-03-22 09:22:25.886,1,NaN,NaN,NaN,R2ST6OORNLR2CO,Great blender,"Love this blender, it works great, very durabl...",5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
csv_path = "data/processed/analytics/products_raw.csv"
save_to_csv(df, csv_path)
print(f"Saved to {csv_path}")

print("\n=== Chunked State ===")
stats = chunked_stats(csv_path)
print(f"Global mean rating: {stats['global_mean']:.2f}")
print(f"Total rows: {stats['total_rows']}")
print(f"\nPer-source stats:")
print(stats['lang_df'])

INFO:analytics.data_loader:Saved 1427 rows → data/processed/analytics/products_raw.csv
INFO:analytics.data_loader:Chunked stats: path=data/processed/analytics/products_raw.csv chunk_size=200

Saved to data/processed/analytics/products_raw.csv

=== Chunked State ===

INFO:analytics.data_loader:Chunked stats complete: total_rows=1427 global_mean=4.8747

Global mean rating: 4.87
Total rows: 1427

Per-source stats:
                        language  mean_rating  review_count
0                     API Source     4.867647         204.0
1                  ecommerce_api     4.875000          96.0
2            reviews_page_1.json     4.875000          40.0
3            reviews_page_2.json     4.875000          40.0
4            reviews_page_3.json     4.875000          40.0
5  ../../data/raw/csv/sample.csv     5.000000           8.0
6  ../../data/raw/xml/sample.xml     5.000000           3.0

In [14]:
print("\n=== Memory Optimisation ===")
df_opt = optimise_dtypes(df)
mem = memory_comparison(df, df_opt)
print(f"Before: {mem['before_mb']:.2f} MB")
print(f"After: {mem['after_mb']:.2f} MB")
print(f"Saved: {mem['reduction_pct']:.1f} MB")

INFO:analytics.data_loader:Memory: 2.76 MB → 2.65 MB (reduction 3.9%)

=== Memory Optimisation ===
Before: 2.76 MB
After: 2.65 MB
Saved: 3.9 MB

In [15]:
print("=== Shape ===")
print(f"Rows: {df.shape[0]}, Columns: {df.shape[1]}")

print("\n=== Info ===")
df.info()

print("\n=== Describe ===")
df.describe()

=== Shape ===
Rows: 1427, Columns: 58

=== Info ===
<class 'pandas.DataFrame'>
RangeIndex: 1427 entries, 0 to 1426
Data columns (total 58 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   source           1427 non-null   str
 1   fetched_at       1427 non-null   datetime64[us]
 2   version          1427 non-null   int64
 3   file_name        1191 non-null   str
 4   type             1191 non-null   str
 5   page_number      305 non-null    float64
 6   review_id        440 non-null    str
 7   title            1110 non-null   str
 8   comment          435 non-null    str
 9   rating           835 non-null    str
 10  author           432 non-null    str
 11  author_id        435 non-null    str
 12  date             547 non-null    str
 13  verified         435 non-null    object
 14  helpful_votes    363 non-null    str
 15  review_link      440 non-null    str
 16  variant.Style    420 non-null    str
 17  variant          15 non-null     str
 18  text             21 non-null     str
 19  text.paragraphs  8 non-null      str
 20  text.tables      13 non-null     str
 21  category         189 non-null    str
 22  description      196 non-null    str
 23  budgeted         84 non-null     float64
 24  actual           84 non-null     float64
 25  variance         0 non-null      float64
 26  variance_pct     0 non-null      float64
 27  status           0 non-null      float64
 28  notes            0 non-null      float64
 29  amount           105 non-null    float64
 30  type             105 non-null    str
 31  running_balance  0 non-null      float64
 32  receipt          105 non-null    str
 33  goal_name        35 non-null     str
 34  target           35 non-null     float64
 35  saved            35 non-null     float64
 36  remaining        0 non-null      float64
 37  progress         0 non-null      float64
 38  eta              35 non-null     str
 39  month            42 non-null     str
 40  income           42 non-null     float64
 41  expenses         42 non-null     float64
 42  savings          42 non-null     float64
 43  net_flow         0 non-null      float64
 44  savings_rate     0 non-null      float64
 45  text.column_1    5 non-null      str
 46  text.column_2    5 non-null      str
 47  text.full_text   5 non-null      str
 48  price            400 non-null    str
 49  link             400 non-null    str
 50  page_scraped     300 non-null    float64
 51  year             275 non-null    float64
 52  awards           275 non-null    float64
 53  nominations      275 non-null    float64
 54  best_picture     20 non-null     object
 55  year_scraped     275 non-null    float64
 56  raw              5 non-null      str
 57  preprocessed     5 non-null      str
dtypes: datetime64[us](1), float64(23), int64(1), object(2), str(31)
memory usage: 646.7+ KB

=== Describe ===

,fetched_at,version,page_number,budgeted,actual,variance,variance_pct,status,notes,amount,...,income,expenses,savings,net_flow,savings_rate,page_scraped,year,awards,nominations,year_scraped
count,1427,1427.0,305.000000,84.000000,84.000000,0.0,0.0,0.0,0.0,105.000000,...,42.000000,42.000000,42.000000,0.0,0.0,300.000000,275.000000,275.000000,275.000000,275.000000
mean,2026-04-03 01:09:07.442710,1.0,1.983607,196.666667,197.333333,NaN,NaN,NaN,NaN,50.566667,...,1261.666667,1006.333333,99.166667,NaN,NaN,2.000000,2011.472727,1.763636,4.018182,2011.472727
min,2026-03-22 09:22:25.843000,1.0,1.000000,50.000000,48.000000,NaN,NaN,NaN,NaN,-400.000000,...,1100.000000,980.000000,50.000000,NaN,NaN,1.000000,2010.000000,1.000000,1.000000,2010.000000
25%,2026-03-26 16:38:31.817000,1.0,1.000000,77.500000,83.750000,NaN,NaN,NaN,NaN,-55.000000,...,1200.000000,990.000000,90.000000,NaN,NaN,1.000000,2011.000000,1.000000,1.000000,2011.000000
50%,2026-04-04 12:20:20.681000,1.0,2.000000,175.000000,175.000000,NaN,NaN,NaN,NaN,-25.000000,...,1285.000000,1004.000000,107.500000,NaN,NaN,2.000000,2011.000000,1.000000,3.000000,2011.000000
75%,2026-04-10 11:59:44.547500,1.0,3.000000,262.500000,262.500000,NaN,NaN,NaN,NaN,250.000000,...,1350.000000,1010.000000,120.000000,NaN,NaN,3.000000,2012.000000,2.000000,6.000000,2012.000000
max,2026-04-10 12:02:53.230000,1.0,3.000000,450.000000,460.000000,NaN,NaN,NaN,NaN,450.000000,...,1350.000000,1050.000000,120.000000,NaN,NaN,3.000000,2013.000000,7.000000,12.000000,2013.000000
std,NaN,0.0,0.821019,127.669881,131.253487,NaN,NaN,NaN,NaN,217.825884,...,91.542784,22.340673,24.863448,NaN,NaN,0.817861,1.078228,1.295185,3.425382,1.078228

In [16]:
import importlib
import analytics.explorer as explorer_module
importlib.reload(explorer_module)
from analytics.explorer import value_counts_report, extract_review_year, plot_distributions

In [17]:
from analytics.explorer import value_counts_report, extract_review_year, plot_distributions

df = extract_review_year(df)

report = value_counts_report(df)
for col, data in report.items():
    print(f"\n{col} ({data['nunique']} unique values):")
    print(data['counts'])
    
plot_distributions(df, "data/processed/analytics/distributions.png")
print("\nChart saved!")

c:\Users\merim\Desktop\E-Commerce-Product-Intelligence\src\analytics\explorer.py:50: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['review_year'] = pd.to_datetime(
INFO:analytics.explorer:Extracted review_year: 105 non-null
INFO:analytics.explorer:source: 16 unique values
INFO:analytics.explorer:status: 0 unique values
INFO:analytics.explorer:category: 16 unique values
INFO:analytics.explorer:verified: 3 unique values

source (16 unique values):
source
https://books.toscrape.com                                400
https://www.scrapethissite.com/pages/ajax-javascript/     275
../../data/raw/excel/student_finance_data.xlsx            273
API Source                                                204
ecommerce_api                                              96
reviews_page_1.json                                        40
reviews_page_2.json                                        40
reviews_page_3.json                                        40
../../data/raw/csv/sample.csv                              15
../../data/raw/pdf/student_finance_normal.pdf               8
../../data/raw/pdf/student_finance_twocol.pdf               8
../../data/raw/word/student_finance_report.docx             8
../../data/raw/xml/sample.xml                               5
../../data/raw/word/student_finance_report_twocol.docx      5
../../data/raw/images/test_scan.png                         5
Name: count, dtype: int64

status (0 unique values):
Series([], Name: count, dtype: int64)

category (16 unique values):
category
EXPENSE          49
INCOME           35
Employment       14
Food              7
Transport         7
Grant             7
Books             7
Freelance         7
Entertainment     7
Health            7
Savings           7
Housing           7
Family            7
Utilities         7
Misc              7
Name: count, dtype: int64

verified (3 unique values):
verified
True                                            423
 2026                                             8
Reviewed in the United States on February 27      4
Name: count, dtype: int64

INFO:analytics.explorer:Saved distribution chart → data/processed/analytics/distributions.png

Chart saved!

In [18]:
import os
from dotenv import load_dotenv
load_dotenv()
print(os.getenv("CLIENT_SECRET_FILE"))
print(os.path.exists(os.getenv("CLIENT_SECRET_FILE")))

google_drive/credentials.json
True

In [19]:
import os
os.environ["CLIENT_SECRET_FILE"] = "google_drive/credentials.json"

from utils.upload_utils import upload_image
import importlib
import utils.upload_utils as upload_module
importlib.reload(upload_module)
from utils.upload_utils import upload_image

chart_path = "data/processed/analytics/distributions.png"
file_url = upload_image(chart_path)
print(f"Chart uploaded: {file_url}")

c:\Users\merim\Desktop\E-Commerce-Product-Intelligence\.venv\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.3.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(
INFO:googleapiclient.discovery_cache:file_cache is only supported with oauth2client<4.0.0

Uploaded distributions.png -> https://drive.google.com/file/d/12TmpG-CrQVEDNc5ow40ClK1NOp6gnzYN/view
Chart uploaded: https://drive.google.com/file/d/12TmpG-CrQVEDNc5ow40ClK1NOp6gnzYN/view

In [20]:
import importlib
import analytics.selector as selector_module
importlib.reload(selector_module)
from analytics.selector import select_columns, loc_filter, iloc_sample, boolean_filter, isin_filter, between_filter

In [21]:
#Part 5

print("=== select_columns ===")
cols = select_columns(df, ['title', 'rating', 'source', 'helpful_votes'])
print(cols.head(3))

print("\n=== loc filter (rating >= 4.0) ===")
high_rated = loc_filter(df, min_rating=4.0)
print(f"Rows: {len(high_rated)}")
print(high_rated.head(3))

print("\n=== iloc sample ===")
sampled = iloc_sample(df, step=100)
print(f"Rows: {len(sampled)}")

print("\n=== boolean filter ===")
quality = boolean_filter(df, min_rating=4.0, max_rating=5.0)
print(f"Rows: {len(quality)}")

print("\n=== isin filter ===")
api_reviews = isin_filter(df)
print(f"Rows: {len(api_reviews)}")

print("\n=== between filter ===")
mid_range = between_filter(df, col='rating', low=3.0, high=4.5)
print(f"Rows: {len(mid_range)}")

INFO:analytics.selector:Selecting 4/4 columns
INFO:analytics.selector:loc filter (vote_avg >= 4.0): 431 rows
INFO:analytics.selector:iloc sample (step=100): 15 rows
INFO:analytics.selector:boolean_filter: 431 rows match
INFO:analytics.selector:isin_filter (exclude=False): 420 rows
INFO:analytics.selector:between_filter rating [3.0, 4.5]: 54 rows

=== select_columns ===
                                      title rating               source  \
0  Powerful, Versatile & Worth Every Penny!      5  reviews_page_1.json
1         Powerful and versatile — love it!      5  reviews_page_1.json
2                             Great blender      5  reviews_page_1.json

                 helpful_votes
0  8 people found this helpful
1  6 people found this helpful
2                          NaN

=== loc filter (rating >= 4.0) ===
Rows: 431
                                      title rating  \
0  Powerful, Versatile & Worth Every Penny!      5
1         Powerful and versatile — love it!      5
2                             Great blender      5

                 helpful_votes               source
0  8 people found this helpful  reviews_page_1.json
1  6 people found this helpful  reviews_page_1.json
2                          NaN  reviews_page_1.json

=== iloc sample ===
Rows: 15

=== boolean filter ===
Rows: 431

=== isin filter ===
Rows: 420

=== between filter ===
Rows: 54

In [22]:
# Part 7
print("=== Missing Values ===")
missing = df.isna().sum()
missing_pct = (missing / len(df) * 100).round(1)
missing_df = pd.DataFrame({'missing': missing, 'pct': missing_pct})
missing_df = missing_df[missing_df['missing'] > 0].sort_values('missing', ascending=False)
print(missing_df)

=== Missing Values ===
                 missing    pct
variance            1427  100.0
variance_pct        1427  100.0
net_flow            1427  100.0
progress            1427  100.0
remaining           1427  100.0
running_balance     1427  100.0
notes               1427  100.0
status              1427  100.0
savings_rate        1427  100.0
text.column_1       1422   99.6
raw                 1422   99.6
text.column_2       1422   99.6
text.full_text      1422   99.6
preprocessed        1422   99.6
text.paragraphs     1419   99.4
text.tables         1414   99.1
variant             1412   98.9
best_picture        1407   98.6
text                1406   98.5
saved               1392   97.5
goal_name           1392   97.5
target              1392   97.5
eta                 1392   97.5
income              1385   97.1
savings             1385   97.1
expenses            1385   97.1
month               1385   97.1
actual              1343   94.1
budgeted            1343   94.1
type                1322   92.6
receipt             1322   92.6
amount              1322   92.6
review_year         1322   92.6
category            1238   86.8
description         1231   86.3
nominations         1152   80.7
year_scraped        1152   80.7
awards              1152   80.7
year                1152   80.7
page_scraped        1127   79.0
page_number         1122   78.6
helpful_votes       1064   74.6
link                1027   72.0
price               1027   72.0
variant.Style       1007   70.6
author               995   69.7
comment              992   69.5
verified             992   69.5
author_id            992   69.5
review_id            987   69.2
review_link          987   69.2
date                 880   61.7
rating               592   41.5
title                317   22.2
file_name            236   16.5
type                 236   16.5

In [23]:
#Part 7 - Heatmap

import matplotlib.pyplot as plt
import matplotlib
matplotlib.use('Agg')

# Uzmi samo kolone sa missing vrijednostima
cols_with_missing = missing_df.index.tolist()[:20]  # top 20
df_missing = df[cols_with_missing].isna()

fig, ax = plt.subplots(figsize=(14, 8))
im = ax.imshow(df_missing.T.values, aspect='auto', cmap='RdYlGn_r')
ax.set_yticks(range(len(cols_with_missing)))
ax.set_yticklabels(cols_with_missing, fontsize=8)
ax.set_xlabel('Row index')
ax.set_title('Missing Value Heatmap (red = missing)')
plt.colorbar(im, ax=ax)
plt.tight_layout()
plt.savefig('data/processed/analytics/missing_heatmap.png', dpi=120, bbox_inches='tight')
print("Heatmap saved!")

Heatmap saved!

In [24]:
import sys
sys.path.append('src')

import importlib
import analytics.regex_ops as regex_module
importlib.reload(regex_module)
from analytics.regex_ops import (extract_year_from_title, filter_titles_starting_with,
                                  extract_number_from_title, positive_comment_count,
                                  short_comments, extract_categories, top_categories,
                                  validate_review_id)

In [25]:
print("=== Year from title ===")
years = extract_year_from_title(df['title'].dropna())
print(f"Titles with year: {years.notna().sum()}")

print("\n=== Titles starting with 'The' ===")
the_titles = filter_titles_starting_with(df, prefix='The')
print(f"Count: {len(the_titles)}")

print("\n=== Numbers in titles ===")
df_num = extract_number_from_title(df)
print(df_num[['title', 'title_number']].dropna(subset=['title_number']).head(5))

print("\n=== Positive comments ===")
count = positive_comment_count(df)
print(f"Count: {count}")

print("\n=== Short comments ===")
short = short_comments(df, max_chars=50)
print(f"Count: {len(short)}")

print("\n=== Categories ===")
df_cat = extract_categories(df)
print(top_categories(df_cat, n=10))

print("\n=== Validate review ID ===")
print(validate_review_id("R3HIEYXVQFRUBV"))
print(validate_review_id("invalid123"))

INFO:analytics.regex_ops:Titles with year in parentheses: 0
INFO:analytics.regex_ops:Titles starting with "The": 175
INFO:analytics.regex_ops:Titles containing a number: 125
c:\Users\merim\Desktop\E-Commerce-Product-Intelligence\src\analytics\regex_ops.py:40: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  mask  = df['comment'].str.contains(_PRODUCT_TERMS.pattern,
INFO:analytics.regex_ops:Positive comments : 383
INFO:analytics.regex_ops:Very short comments (<50 chars): 7
INFO:analytics.regex_ops:Rows with extracted categories: 189

=== Year from title ===
Titles with year: 0

=== Titles starting with 'The' ===
Count: 175

=== Numbers in titles ===
                   title title_number
7   100% would recommend          100
15  100% would recommend          100
23  100% would recommend          100
35  100% would recommend          100
43  100% would recommend          100

=== Positive comments ===
Count: 383

=== Short comments ===
Count: 7

=== Categories ===
[('EXPENSE', 49), ('INCOME', 35), ('Employment', 14), ('Food', 7), ('Transport', 7), ('Grant', 7), ('Books', 7), ('Freelance', 7), ('Entertainment', 7), ('Health', 7)]

=== Validate review ID ===
True
False

In [26]:
# Part 7 - Quality Report
import importlib
import analytics.quality_report as qr_module
importlib.reload(qr_module)
from analytics.quality_report import full_quality_report, save_missing_heatmap

print("=== Full Quality Report ===")
quality_df = full_quality_report(df)
print(quality_df)

# Save as CSV
quality_df.to_csv('data/processed/analytics/quality_report.csv', index=False)
print("\nQuality report saved!")

# Save heatmap
save_missing_heatmap(df, 'data/processed/analytics/missing_heatmap.png')
print("Heatmap saved!")

INFO:analytics.quality_report:Columns with missing values: 56
INFO:analytics.quality_report:Zero-as-missing check complete for: ['budgeted', 'actual']
INFO:analytics.quality_report:Quality report: 58 issues found

=== Full Quality Report ===
             column                         issue  count     pct severity
0      variance_pct                Missing values   1427  100.00     HIGH
1          variance                Missing values   1427  100.00     HIGH
2            status                Missing values   1427  100.00     HIGH
3         remaining                Missing values   1427  100.00     HIGH
4      savings_rate                Missing values   1427  100.00     HIGH
5          net_flow                Missing values   1427  100.00     HIGH
6          progress                Missing values   1427  100.00     HIGH
7             notes                Missing values   1427  100.00     HIGH
8   running_balance                Missing values   1427  100.00     HIGH
9     text.column_1                Missing values   1422   99.65     HIGH
10    text.column_2                Missing values   1422   99.65     HIGH
11   text.full_text                Missing values   1422   99.65     HIGH
12     preprocessed                Missing values   1422   99.65     HIGH
13              raw                Missing values   1422   99.65     HIGH
14  text.paragraphs                Missing values   1419   99.44     HIGH
15      text.tables                Missing values   1414   99.09     HIGH
16          variant                Missing values   1412   98.95     HIGH
17     best_picture                Missing values   1407   98.60     HIGH
18             text                Missing values   1406   98.53     HIGH
19        goal_name                Missing values   1392   97.55     HIGH
20           target                Missing values   1392   97.55     HIGH
21            saved                Missing values   1392   97.55     HIGH
22              eta                Missing values   1392   97.55     HIGH
23         expenses                Missing values   1385   97.06     HIGH
24            month                Missing values   1385   97.06     HIGH
25           income                Missing values   1385   97.06     HIGH
26          savings                Missing values   1385   97.06     HIGH
27         budgeted                Missing values   1343   94.11     HIGH
28           actual                Missing values   1343   94.11     HIGH
56         budgeted  Zero values (likely missing)   1343   94.10     HIGH
57           actual  Zero values (likely missing)   1343   94.10     HIGH
29          receipt                Missing values   1322   92.64     HIGH
30             type                Missing values   1322   92.64     HIGH
31      review_year                Missing values   1322   92.64     HIGH
32           amount                Missing values   1322   92.64     HIGH
33         category                Missing values   1238   86.76     HIGH
34      description                Missing values   1231   86.26     HIGH
35     year_scraped                Missing values   1152   80.73     HIGH
36      nominations                Missing values   1152   80.73     HIGH
37             year                Missing values   1152   80.73     HIGH
38           awards                Missing values   1152   80.73     HIGH
39     page_scraped                Missing values   1127   78.98     HIGH
40      page_number                Missing values   1122   78.63     HIGH
41    helpful_votes                Missing values   1064   74.56     HIGH
42             link                Missing values   1027   71.97     HIGH
43            price                Missing values   1027   71.97     HIGH
44    variant.Style                Missing values   1007   70.57     HIGH
45           author                Missing values    995   69.73     HIGH
46          comment                Missing values    992   69.52     HIGH
47        author_id                Missing values    992   69.52     HIGH
48         verified                Missing values    992   69.52     HIGH
49        review_id                Missing values    987   69.17     HIGH
50      review_link                Missing values    987   69.17     HIGH
51             date                Missing values    880   61.67     HIGH
52           rating                Missing values    592   41.49     HIGH
53            title                Missing values    317   22.21   MEDIUM
54        file_name                Missing values    236   16.54   MEDIUM
55             type                Missing values    236   16.54   MEDIUM

Quality report saved!

INFO:analytics.quality_report:Saved missing heatmap → data/processed/analytics/missing_heatmap.png

Heatmap saved!